# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 23:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('motto', models.CharField(max_length=200)),
                ('base_style', models.CharField(choices=[('SW', 'Super white'), ('DS', 'Dark style')], default='SW', max_length=10)),
                ('banner_image', models.ImageField(upload_to='/banners/')),
                ('advantages', models.TextField()),
                ('contact_phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
