# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('motto', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Page',
        ),
    ]
