# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20161023_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='advantages',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='shop',
            name='base_style',
            field=models.CharField(choices=[('SW', 'Super white'), ('DS', 'Dark style')], default='SW', max_length=10),
        ),
        migrations.AddField(
            model_name='shop',
            name='contact_phone',
            field=models.CharField(default='+7-904-776-30-57', max_length=20),
        ),
        migrations.AddField(
            model_name='shop',
            name='email',
            field=models.EmailField(default='Igor_Yudin@inbox.ru', max_length=254),
        ),
    ]
