# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20161023_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='base_style',
            field=models.CharField(choices=[('DS', 'Dark style'), ('SW', 'Super white')], default='SW', max_length=10),
        ),
    ]
