# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20161023_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='banner_image',
            field=models.ImageField(blank=True, default=True, null=True, upload_to='/banners/'),
        ),
    ]
