# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 21:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_shop_banner_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='banner_image',
        ),
    ]
