# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_remove_shop_banner_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='banner_image',
            field=models.ImageField(blank=True, default=True, null=True, upload_to='/banners/'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='base_style',
            field=models.CharField(choices=[('SW', 'Super white'), ('DS', 'Dark style')], default='SW', max_length=10),
        ),
    ]
