# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 22:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20161024_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='banners'),
        ),
    ]
