# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 15:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20161024_0121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('os', models.CharField(choices=[(12, 'Blackberry OS'), (11, 'iOS'), (9, 'Android'), (8, 'Solaris'), (7, 'Linux'), (3, 'Windows 7'), (5, 'Windows 10'), (10, 'Windows Phone'), (6, 'OS X'), (2, 'Windows Vista'), (4, 'Windows 8'), (1, 'Windows XP')], max_length=20, null=True)),
                ('device', models.CharField(choices=[(2, 'Смартфон'), (1, 'Десктоп')], max_length=20, null=True)),
                ('time_enter', models.DateField(default=django.utils.timezone.now)),
                ('time_escape', models.DateField(blank=True, null=True)),
                ('language', models.CharField(blank=True, default='ru-ru', max_length=100)),
                ('ip', models.CharField(max_length=16)),
                ('country', models.CharField(max_length=30, null=True)),
                ('city', models.CharField(max_length=30, null=True)),
                ('weather', models.CharField(choices=[(6, 'Windy'), (2, 'Cloudy'), (1, 'Sunny'), (3, 'Show'), (4, 'Rain')], max_length=15, null=True)),
                ('season', models.CharField(choices=[(4, 'Winter'), (1, 'Spring'), (3, 'Automn'), (2, 'Summer')], max_length=20, null=True)),
                ('is_selebration', models.BooleanField(default=False)),
                ('day_of_the_week', models.CharField(choices=[(4, 'Thursday'), (5, 'Friday'), (7, 'Sunday'), (2, 'Tuesday'), (1, 'Monday'), (3, 'Wednesday'), (6, 'Saturday')], max_length=15, null=True)),
                ('mood', models.CharField(choices=[(2, 'Good'), (4, 'Bad'), (3, 'Normal'), (1, 'Fine')], max_length=15, null=True)),
                ('result', models.CharField(choices=[(2, "Didn't buy"), (1, 'Buy')], max_length=15, null=True)),
                ('comment', models.TextField(default='')),
                ('browser', models.TextField(choices=[(3, 'Opera'), (5, 'Internet Explorer'), (2, 'Firefox'), (1, 'Chrome'), (4, 'Safari')], max_length=20, null=True)),
            ],
        ),
    ]
