# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_visit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='browser',
            field=models.TextField(choices=[(4, 'Safari'), (2, 'Firefox'), (1, 'Chrome'), (3, 'Opera'), (5, 'Internet Explorer')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='day_of_the_week',
            field=models.CharField(choices=[(4, 'Thursday'), (2, 'Tuesday'), (6, 'Saturday'), (3, 'Wednesday'), (7, 'Sunday'), (5, 'Friday'), (1, 'Monday')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='device',
            field=models.CharField(choices=[(1, 'Десктоп'), (2, 'Смартфон')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='mood',
            field=models.CharField(choices=[(4, 'Bad'), (1, 'Fine'), (3, 'Normal'), (2, 'Good')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='os',
            field=models.CharField(choices=[(7, 'Linux'), (10, 'Windows Phone'), (5, 'Windows 10'), (8, 'Solaris'), (6, 'OS X'), (9, 'Android'), (11, 'iOS'), (1, 'Windows XP'), (12, 'Blackberry OS'), (4, 'Windows 8'), (2, 'Windows Vista'), (3, 'Windows 7')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='season',
            field=models.CharField(choices=[(3, 'Automn'), (2, 'Summer'), (4, 'Winter'), (1, 'Spring')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='weather',
            field=models.CharField(choices=[(1, 'Sunny'), (3, 'Show'), (4, 'Rain'), (6, 'Windy'), (2, 'Cloudy')], max_length=15, null=True),
        ),
    ]
