# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 15:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20161026_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='base_style',
            field=models.CharField(choices=[('DS', 'Dark style'), ('SW', 'Super white')], default='SW', max_length=10),
        ),
        migrations.AlterField(
            model_name='visit',
            name='browser',
            field=models.CharField(choices=[(3, 'Opera'), (2, 'Firefox'), (4, 'Safari'), (5, 'Internet Explorer'), (1, 'Chrome')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='day_of_the_week',
            field=models.CharField(choices=[(7, 'Sunday'), (1, 'Monday'), (6, 'Saturday'), (2, 'Tuesday'), (5, 'Friday'), (4, 'Thursday'), (3, 'Wednesday')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='device',
            field=models.CharField(choices=[(2, 'Smartphone'), (1, 'Desktop')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='mood',
            field=models.CharField(choices=[(1, 'Fine'), (2, 'Good'), (3, 'Normal'), (4, 'Bad')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='os',
            field=models.CharField(choices=[(5, 'Windows 10'), (6, 'OS X'), (1, 'Windows XP'), (3, 'Windows 7'), (7, 'Linux'), (10, 'Windows Phone'), (4, 'Windows 8'), (2, 'Windows Vista'), (9, 'Android'), (11, 'iOS'), (8, 'Solaris'), (12, 'Blackberry OS')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='season',
            field=models.CharField(choices=[(4, 'Winter'), (1, 'Spring'), (3, 'Automn'), (2, 'Summer')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='time_enter',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='visit',
            name='time_escape',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='weather',
            field=models.CharField(choices=[(3, 'Snow'), (4, 'Rain'), (1, 'Sunny'), (6, 'Windy'), (2, 'Cloudy')], max_length=15, null=True),
        ),
    ]
