# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20161026_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='base_style',
            field=models.CharField(choices=[('SW', 'Super white'), ('DS', 'Dark style')], default='SW', max_length=10),
        ),
        migrations.AlterField(
            model_name='visit',
            name='browser',
            field=models.CharField(choices=[(1, 'Chrome'), (2, 'Firefox'), (3, 'Opera'), (4, 'Safari'), (5, 'Internet Explorer')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='comment',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='visit',
            name='day_of_the_week',
            field=models.CharField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='device',
            field=models.CharField(choices=[(1, 'Desktop'), (2, 'Smartphone')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='os',
            field=models.CharField(choices=[(1, 'Windows XP'), (2, 'Windows Vista'), (3, 'Windows 7'), (4, 'Windows 8'), (5, 'Windows 10'), (6, 'OS X'), (7, 'Linux'), (8, 'Solaris'), (9, 'Android'), (10, 'Windows Phone'), (11, 'iOS'), (12, 'Blackberry OS')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='result',
            field=models.CharField(choices=[(1, 'Buy'), (2, "Didn't buy")], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='season',
            field=models.CharField(choices=[(1, 'Spring'), (2, 'Summer'), (3, 'Automn'), (4, 'Winter')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='weather',
            field=models.CharField(choices=[(1, 'Sunny'), (2, 'Cloudy'), (3, 'Snow'), (4, 'Rain'), (6, 'Windy')], max_length=15, null=True),
        ),
    ]
