# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20161026_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='browser',
            field=models.IntegerField(choices=[(1, 'Chrome'), (2, 'Firefox'), (3, 'Opera'), (4, 'Safari'), (5, 'Internet Explorer')], null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='day_of_the_week',
            field=models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='device',
            field=models.IntegerField(choices=[(1, 'Desktop'), (2, 'Smartphone')], null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='mood',
            field=models.IntegerField(choices=[(1, 'Fine'), (2, 'Good'), (3, 'Normal'), (4, 'Bad')], null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='os',
            field=models.IntegerField(choices=[(1, 'Windows XP'), (2, 'Windows Vista'), (3, 'Windows 7'), (4, 'Windows 8'), (5, 'Windows 10'), (6, 'OS X'), (7, 'Linux'), (8, 'Solaris'), (9, 'Android'), (10, 'Windows Phone'), (11, 'iOS'), (12, 'Blackberry OS')], null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='season',
            field=models.IntegerField(choices=[(1, 'Spring'), (2, 'Summer'), (3, 'Automn'), (4, 'Winter')], null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='weather',
            field=models.IntegerField(choices=[(1, 'Sunny'), (2, 'Cloudy'), (3, 'Snow'), (4, 'Rain'), (6, 'Windy')], null=True),
        ),
    ]
