# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_auto_20161026_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='base_style',
            field=models.CharField(choices=[('DS', 'Dark style'), ('SW', 'Super white')], default='SW', max_length=10),
        ),
        migrations.AlterField(
            model_name='visit',
            name='browser',
            field=models.CharField(blank=True, choices=[('Chrome', 'Chrome'), ('Firefox', 'Firefox'), ('Opera', 'Opera'), ('Safari', 'Safari'), ('Internet Explorer', 'Internet Explorer')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='day_of_the_week',
            field=models.CharField(blank=True, choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='device',
            field=models.CharField(blank=True, choices=[('Desktop', 'Desktop'), ('Smartphone', 'Smartphone')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='mood',
            field=models.CharField(blank=True, choices=[('Fine', 'Fine'), ('Good', 'Good'), ('Normal', 'Normal'), ('Bad', 'Bad')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='os',
            field=models.CharField(blank=True, choices=[('Windows XP', 'Windows XP'), ('Windows Vista', 'Windows Vista'), ('Windows 7', 'Windows 7'), ('Windows 8', 'Windows 8'), ('Windows 10', 'Windows 10'), ('Mac OS X', 'Mac OS X'), ('Linux', 'Linux'), ('Solaris', 'Solaris'), ('Android', 'Android'), ('Windows Phone', 'Windows Phone'), ('iOS', 'iOS'), ('Blackberry OS', 'Blackberry OS')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='result',
            field=models.IntegerField(blank=True, choices=[('Buy', 'Buy'), ("Didn't buy", "Didn't buy")], null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='season',
            field=models.IntegerField(blank=True, choices=[('Spring', 'Spring'), ('Summer', 'Summer'), ('Automn', 'Automn'), ('Winter', 'Winter')], null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='weather',
            field=models.CharField(blank=True, choices=[('Sunny', 'Sunny'), ('Cloudy', 'Cloudy'), ('Snow', 'Snow'), ('Rain', 'Rain'), ('Windy', 'Windy')], max_length=100, null=True),
        ),
    ]
