# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_auto_20161026_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='base_style',
            field=models.CharField(choices=[('SW', 'Super white'), ('DS', 'Dark style')], default='SW', max_length=10),
        ),
        migrations.AlterField(
            model_name='visit',
            name='ip',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='result',
            field=models.CharField(blank=True, choices=[('Buy', 'Buy'), ("Didn't buy", "Didn't buy")], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='season',
            field=models.CharField(blank=True, choices=[('Spring', 'Spring'), ('Summer', 'Summer'), ('Automn', 'Automn'), ('Winter', 'Winter')], max_length=100, null=True),
        ),
    ]
