# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 22:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_auto_20161027_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='device',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
