# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_auto_20161027_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='base_style',
            field=models.CharField(choices=[('SW', 'Super white'), ('DS', 'Dark style')], default='SW', max_length=10),
        ),
    ]
